name: Build Image
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: cd990stk4v
          context: .
          file: ./tests/Dockerfile
